apiVersion: v1
kind: ConfigMap

metadata: 
  name: shopapi-cm

data:
  DB_HOST: terraform-20240424111030450100000001.c10kuc2ymwcy.eu-west-2.rds.amazonaws.com
  DB_NAME: bookstore
  DB_USER: appuser
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "1"